services:
    appcoachs.admin.material.qualificationinfo:
        class: Appcoachs\Bundle\MaterialBundle\Admin\QualificationInfoAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Advertiser Review",label: "Advertiser Review" }
        arguments:
            - ~
            - Appcoachs\Bundle\ManageBundle\Document\Qualification
            - AppcoachsMaterialBundle:QualificationInfo
        calls:
            - [setTranslationDomain, [SonataAdminBundle]]

    appcoachs.admin.material.qualificationinfo.review:
        class: Appcoachs\Bundle\MaterialBundle\Admin\QualificationReviewedAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: 'Qualification Review' }
        arguments:
            - ~
            - Appcoachs\Bundle\ManageBundle\Document\QualificationReviewed
            - AppcoachsMaterialBundle:QualificationReviewed
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]

    appcoachs.admin.material.creative:
        class: Appcoachs\Bundle\MaterialBundle\Admin\CreativeAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Creative Review", label: "Creative Review" }
        arguments:
            - ~
            - Appcoachs\Bundle\MaterialBundle\Document\Creative
            - AppcoachsMaterialBundle:Creative
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]



    appcoachs.material.media:
        class: Appcoachs\Bundle\MaterialBundle\Admin\MediaAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Media Management", label: "Media Management" }
        arguments:
            - ~
            - Appcoachs\Bundle\MaterialBundle\Document\Media
            - AppcoachsMaterialBundle:Media
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]

    appcoachs.admin.material.mediamanagement:
        class: Appcoachs\Bundle\MaterialBundle\Admin\MediaManagementAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Media Management", label: "Media Management" }
        arguments:
            - ~
            - Appcoachs\Bundle\MaterialBundle\Document\MediaManagement
            - AppcoachsMaterialBundle:MediaManagement
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]