parameters:
    sonata.material.admin.material.class: Appcoachs\Bundle\MaterialBundle\Admin\MaterialAdmin

services:
    appcoachs.admin.material.qualification:
        class: Appcoachs\Bundle\MaterialBundle\Admin\QualificationAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: "Advertiser Review" }
        arguments:
            - ~
            - Appcoachs\Bundle\ManageBundle\Document\Qualification
            - AppcoachsMaterialBundle:Qualification
        calls:
            - [setTranslationDomain, [SonataAdminBundle]]


    appcoachs.admin.material.creative:
        class: Appcoachs\Bundle\MaterialBundle\Admin\CreativeAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Creative Review", label: "Creative Review" }
        arguments:
            - ~
            - Appcoachs\Bundle\ManageBundle\Document\Creative
            - AppcoachsMaterialBundle:Creative
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]