<?php

namespace Appcoachs\Bundle\MaterialBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Toutiaologs
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Toutiaologs extends DocumentRepository
{
}